[workspace]
default-members = ["services/zero2prod-backend", "common"]
members = ["services/zero2prod-backend", "xtask", "common", "services/zero2prod-common", "services/zero2prod-frontend/crate"]
resolver = "2"
