version: '3.8'

services:

  frontend:
    build:
      context: ./services/zero2prod-frontend
      dockerfile: Dockerfile
    ports:
      - 80

  gateway:
    build:
      context: ./services/zero2prod-gateway
      dockerfile: Dockerfile
    ports:
      - 80:80
      - 443:443
    depends_on:
      - frontend
    volumes:
      - ./logs:/var/log/nginx
      - /etc/letsencrypt
      - /var/www/certbot/live/area403.org

  certbot:
    image: certbot/certbot
    restart: unless-stopped
    volumes:
      - /etc/letsencrypt
      - /var/www/certbot
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"
