version: '3.8'

services:

  frontend:
    build:
      context: ./services/zero2prod-frontend
      dockerfile: Dockerfile
    ports:
      - 80

  gateway:
    build:
      context: ./services/zero2prod-gateway
      dockerfile: Dockerfile
    ports:
      - 80:80
      - 443:443
    depends_on:
      - frontend
    volumes:
      - ./logs:/var/log/nginx
