version: "3.8"
services:
  db:
    image: "postgres:14"
    ports:
      - "5436:5432"
    environment:
      - POSTGRES_USER=bob
      - POSTGRES_PASSWORD=secret
      - POSTGRES_DB=newsletter

  zero2prod:
    image:
      zero2prod:latest
    ports:
      - "8085:8000"
    depends_on:
      - db
    environment:
      - ZERO2PROD__DATABASE__USERNAME=bob
      - ZERO2PROD__DATABASE__PASSWORD=secret
      - ZERO2PROD__DATABASE__HOST=db
      - ZERO2PROD__DATABASE__PORT=5432
