[package]
name = "zero2prod-web"
version = "0.1.0"
edition = "2021"

[dependencies]
gloo-net = "^0.3.0"
console_error_panic_hook = "^0.1.7"
yew = { version = "^0.20.0", features = ["csr"] }
yew-router = "^0.17.0"
wasm-bindgen-futures = "0.4.37"
wasm-logger = "0.2.0"
